apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: env-params
  namespace: external-secrets
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secretmanager
  target:
    name: env-params
    creationPolicy: CreateOrMerge
  dataFrom:
  - extract:
      key: "${projectName}-env-params"
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alb-params
  namespace: external-secrets
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secretmanager
  target:
    name: alb-params
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: "${projectName}-alb-params"
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oidc-params
  namespace: external-secrets
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secretmanager
  target:
    name: oidc-params
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: "${projectName}-keycloak"