apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: webapp-route
  labels:
    app: webapp
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: webapp-gateway
      sectionName: https
  rules:
    - backendRefs:
        - name: webapp
          port: 80