apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: envoy-kube-proxy
resources:
  - ../base
  - TargetGroupConfiguration.yaml
  - ListenerRuleConfiguration.yaml
  - ../gateway
  - ../rbac

patches:
  - path: patch-deployment.yaml
  - path: patch-httproute.yaml