apiVersion: fluxcd.controlplane.io/v1
kind: FluxInstance
metadata:
  name: flux
  namespace: flux-system
spec:
  sync:
    kind: GitRepository
    url: "https://github.com/AleksandrSor/demo-infra.git"
    ref: "refs/heads/main"
    path: "fluxcd/clusters/prod"
    pullSecret: "demo-infra"
    provider: github
    interval: 5m
  kustomize:  
    patches:
      - target:
          kind: Deployment
        patch: |-
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: all
          spec:
            template:
              spec:
                affinity:
                  nodeAffinity:
                    requiredDuringSchedulingIgnoredDuringExecution:
                      nodeSelectorTerms:
                        - matchExpressions:
                            - key: role.core
                              operator: Exists
                tolerations:
                  - key: CriticalAddonsOnly
                    operator: Exists
                    effect: NoSchedule
                  - key: role.core
                    operator: Exists
                    effect: NoSchedule