apiVersion: fluxcd.controlplane.io/v1
kind: FluxInstance
metadata:
  name: flux
  namespace: flux-system
spec:
  sync:
    kind: GitRepository
    url: "https://github.com/AleksandrSor/demo-infra.git"
    ref: "refs/heads/feature/fluxcd"
    path: "fluxcd/clusters/prod"
    pullSecret: "demo-infra"
    provider: github
    interval: 5m