apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  values:
    provider:
      name: aws
    env:
      - name: AWS_DEFAULT_REGION
        value: us-east-1
    txtOwnerId: demo-infra-prod
    txtPrefix: demo-infra-prod
    policy: sync