apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: envoy-kube-proxy
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./fluxcd/infra/envoy-kube-proxy/prod
  dependsOn:
    - name: aws-load-balancer-controller
    - name: external-secrets-custom
  prune: true
  interval: 30m
  timeout: 5m
  postBuild:
    substituteFrom:
      - kind: Secret
        name: env-params
      - kind: Secret
        name: oidc-params