apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets-custom
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./fluxcd/infra/external-secrets-custom/prod
  dependsOn:
  - name: external-secrets
  prune: true
  interval: 30m
  timeout: 5m
  postBuild:
    substitute:
      projectName: demo-infra
      region: us-east-1
    substituteFrom:
      - kind: Secret
        name: env-params
        optional: true