apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-instance
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./fluxcd/infra/flux-instance/prod
  dependsOn:
    - name: flux-operator
  prune: true
  interval: 30m
  retryInterval: 5m
  timeout: 5m
  postBuild:
    substitute:
      gitRef: "refs/heads/prod"
      gitUrl: "https://github.com/AleksandrSor/demo-infra.git"
      gitSecret: "demo-infra"