apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prod-webapp
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./fluxcd/app/front/webapp/prod
  prune: true
  targetNamespace: prod-webapp
  interval: 10m
  timeout: 5m
  dependsOn:
    - name: aws-load-balancer-gateway-customization
  images:
    - name: ghcr.io/stefanprodan/podinfo
      newTag: 6.14.0
  postBuild:
    substituteFrom:
      - kind: Secret
        name: env-params