env:
  region: us-east-1
  tf_user:
    name: tf-user
    path: "/automation/iac/"
  tf_role_name: TFExecutionRole
  tf_extra_admin_users: 
    - "terraf1admin"
  repository:
    name: AleksandrSor/demo-infra
    protected_environment: production
project:
  name: &project_name demo-infra
network:
  vpc_cidr: "10.10.0.0/16"
  vpc_secondary_cidr: "100.64.0.0/16"
  node_subnets:
    node-1:
      cidr: "10.51.0.0/19"
      az: &node1az us-east-1a
    node-2:
      cidr: "10.51.32.0/19"
      az: &node2az us-east-1b
  pod_subnets:
    pod-1:
      cidr: "100.64.0.0/17"
      az: *node1az
    pod-2:
      cidr: "100.64.128.0/17"
      az: *node2az
  alb_subnets:
    alb-1:
      cidr: "10.10.128.0/19"
      az: *node1az
    alb-2:
      cidr: "10.10.160.0/19"
      az: *node2az
common_tags:
  Project: *project_name
  Environment: Development
  Owner: DevOps Team