name: deploy-IaC
on:
  workflow_call:

env:
  tg_version: '1.0.1'
  tofu_version: '1.12.0-beta1'
  working_dir: './IaC'

permissions:
  contents: read  # Required for checkout and gitleaks
  id-token: write # Required to request OIDC token for Terraform Cloud API authentication

jobs:
  deploy:
    name: IaC Deploy
    environment: 
      name: production
      deployment: true
    runs-on: ubuntu-24.04-arm
    env:
      TF_VAR_public_access_cidrs: ${{ vars.EKS_PUBLIC_ACCESS_CIDRS }}
      TF_VAR_eks_oidc_provider_config: ${{ secrets.EKS_OIDC_PROVIDER_CONFIG }}
    defaults:
      run:
        working-directory: ${{ env.working_dir }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
    
      - name: Configure AWS Credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
            aws-region: ${{ vars.AWS_REGION }}
            role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME_ARN }}
            output-credentials: true

      - name: get caller identity
        run: |
            aws sts get-caller-identity
      
      - name: Install terragrunt and tofu
        uses: gruntwork-io/terragrunt-action@v3
        with:
          tofu_version: ${{ env.tofu_version }}
          tg_version: ${{ env.tg_version }}

      - name: Apply terragrunt configuration
        run: |
          echo "### Terragrunt Apply Output" >> $GITHUB_STEP_SUMMARY
          echo '```terraform' >> $GITHUB_STEP_SUMMARY
          terragrunt run --all --non-interactive --log-format bare -- apply -auto-approve >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY