name: plan-IaC
on:
  workflow_call:

env:
  tg_version: '1.0.1'
  tofu_version: '1.12.0-beta1'
  working_dir: './IaC'

permissions:
  contents: read  # Required for checkout and gitleaks
  id-token: write # Required to request OIDC token for Terraform Cloud API authentication

jobs:
  plan:
    name: terragrunt-plan
    environment: 
      name: production
      deployment: false
    runs-on: ubuntu-24.04-arm
    env:
      DEPLOY_ENV: production
      TF_VAR_public_access_cidrs: ${{ vars.EKS_PUBLIC_ACCESS_CIDRS }}
      KEYCLOAK_URL: ${{ vars.KEYCLOAK_URL }}
      KEYCLOAK_REALM: ${{ vars.KEYCLOAK_REALM }}
      KEYCLOAK_BASE_PATH: ${{ vars.KEYCLOAK_BASE_PATH }}
    defaults:
      run:
        working-directory: ${{ env.working_dir }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
        # for pull request target
        #  ref: refs/pull/${{ github.event.number }}/merge
        # It is running against protected environment, which requires PR to be approved
        # so consider it as safe to checkout merge_request code
    
      - name: Configure AWS Credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
            aws-region: ${{ vars.AWS_REGION }}
            role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME_ARN }}
            output-credentials: true

      - name: get caller identity
        run: |
            aws sts get-caller-identity

      - id: keycloak-token
        name: Get KC token
        uses: ./.github/actions/keycloak-token
        with:
          keycloak-url: ${{ env.KEYCLOAK_URL }}
          keycloak-realm: ${{ env.KEYCLOAK_REALM }}
          keycloak-client-id: repo:${{ github.repository }}:environment:${{ env.DEPLOY_ENV }}
          keycloak-base-path: ${{ env.KEYCLOAK_BASE_PATH || ''}}
      
      - name: Install terragrunt and tofu
        uses: gruntwork-io/terragrunt-action@v3
        with:
          tofu_version: ${{ env.tofu_version }}
          tg_version: ${{ env.tg_version }}

      - name: Plan terragrunt configuration
        env:
          KEYCLOAK_TOKEN: ${{ steps.keycloak-token.outputs.access-token }}
          KEYCLOAK_CLIENT_ID: ${{ vars.KEYCLOAK_CLIENT_ID }}
        run: |
          echo "### 🏗️ Terragrunt Plan Output" >> $GITHUB_STEP_SUMMARY
          echo '```terraform' >> $GITHUB_STEP_SUMMARY
          terragrunt run --all --non-interactive --log-format bare -- plan >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY