name: trivy
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - 'feature/**'
jobs:
  scan:
    name: trivy
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run Trivy vulnerability scanner in fs mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          hide-progress: true
          format: 'table'
          exit-code: '1' # Fails the build if issues are found
          severity: 'CRITICAL,HIGH'