name: test JWT
on:
  push:
    branches:
      - feature/keycloack

permissions:
  id-token: write
  contents: read



jobs:
  test-jwt:
    runs-on: ubuntu-24.04-arm
    environment: 
      name: test-keycloak
      deployment: false
    env:
      KEYCLOAK_URL: ${{ vars.KEYCLOAK_URL }}
      KEYCLOAK_REALM: ${{ vars.KEYCLOAK_REALM }}
      KEYCLOAK_AUDIENCE: "${{ vars.KEYCLOAK_URL }}/auth/realms/${{ vars.KEYCLOAK_REALM }}"
    steps:
      - name: Get JWT token
        id: get-gh-token
        uses: actions/github-script@v9
        with:
          script: |
            const audience = process.env['KEYCLOAK_AUDIENCE'];
            let ghToken = await core.getIDToken(audience);
            core.setOutput('ghToken', ghToken);

            function decodeJWT(jwtToken) {
              try {
                // A JWT has 3 parts: Header, Payload, Signature
                const [header, payload, signature] = jwtToken.split('.');
                
                // Decode base64url string to standard UTF-8 text
                const decodedPayload = Buffer.from(payload, 'base64').toString('utf8');
                
                // Parse the string into a readable JavaScript object
                return JSON.parse(decodedPayload);
              } catch (error) {
                console.error("Invalid JWT format", error);
                return null;
              }
            }

            console.log('----');
            console.log(decodeJWT(ghToken));
            console.log('----');
      - name: Get KC token
        id: get-kc-token
        run: |
          KEYCLOAK_RESPONSE=$(curl -s "$KEYCLOAK_URL/auth/realms/$KEYCLOAK_REALM/protocol/openid-connect/token" \
            -H 'Content-Type: application/x-www-form-urlencoded' \
            -d 'grant_type=urn:ietf:params:oauth:grant-type:jwt-bearer' \
            -d 'assertion=${{ steps.get-gh-token.outputs.ghToken }}' \
            -d 'scope=openid' \
            -d 'client_id=repo:AleksandrSor/demo-infra:environment:test-keycloak' \
            -d 'client_assertion_type=urn:ietf:params:oauth:client-assertion-type:jwt-bearer' \
            -d 'client_assertion=${{ steps.get-gh-token.outputs.ghToken }}' | jq -r '.')
          echo ${KEYCLOAK_RESPONSE}
  test-keycloak:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Get JWT token
        run: |
          GH_TOKEN=$(curl -s "$ACTIONS_ID_TOKEN_REQUEST_URL" \
            -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" | jq -r '.value')
          echo "ghToken=${GH_TOKEN}" >> $GITHUB_OUTPUT
          echo "----"
          echo "${GH_TOKEN}" | jq -R 'split(".") | .[0],.[1] | @base64d | fromjson'
          echo "----"

        id: get-token
              
