name: scan-trivy
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - 'feature/**'

permissions:
  security-events: write  # Required to upload SARIF results
      
jobs:
  scan:
    name: trivy
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run Trivy vulnerability scanner in fs mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          hide-progress: true
          format: 'sarif'            # Generates SARIF format
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'  # Filter for high-impact issues
          exit-code: '1'              # Exitif vulnerabilities are found

      - name: Upload SARIF results
        uses: github/codeql-action/upload-sarif@v3
        if: always()                 # Ensure results upload even if scan finds issues
        with:
          sarif_file: 'trivy-results.sarif'

      - name: Convert SARIF to Markdown
        if: always()                 # Ensure results upload even if scan finds issues
        id: sarif-to-markdown
        uses: 11notes/action-sarif-to-markdown@v1.0.0
        with:
          sarif_file: 'trivy-results.sarif'

      - name: Add to Job Summary
        if: always()                 # Ensure results upload even if scan finds issues  
        run: echo ${{ steps.sarif-to-markdown.outputs.markdown }} >> $GITHUB_STEP_SUMMARY