name: validate-IaC
on:
  workflow_call:

env:
  tg_version: '1.0.1'
  tofu_version: '1.12.0-beta1'
  working_dir: './IaC'
  IAC_QUICK_CHECK: 'true' # disable backend generation and some dependancies check

jobs:
  scan:
    name: terragrunt-validate
    runs-on: ubuntu-24.04-arm
    defaults:
      run:
        working-directory: ${{ env.working_dir }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Install terragrunt and tofu
        uses: gruntwork-io/terragrunt-action@v3
        with:
          tofu_version: ${{ env.tofu_version }}
          tg_version: ${{ env.tg_version }}

      - name: Check terragrunt hcl formatting
        run: |
          hcl fmt --check --diff

      - name: Validate terragrunt HCL config
        run: |
          hcl validate

      # Not find better way to validate the terraform code, since terragrunt always try to fetch remote state
      - name: Validate tofu charts
        run: |
          terragrunt validate --all